

# 接口
server:
  post: 8080

# 名称
spring:
  application:
    name: user-system

  # 环境配置
  profiles:
    active: dev
    # active: test
    # active: prod

  # Nacos
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
      config:
        server-addr: nacos:8848
        file-extension: yaml
        import-check:
          enabled: false

# MyBatis-Plus 配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl