spring:
  # postgreSQL
  datasource:
    url: jdbc:postgresql://postgres:5432/dog
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  # Redis 配置
  data:
    redis:
      host: redis
      port: 6379
      password: 123456
      jedis:
        pool:
          max-active: 8
          max-idle: 8

# EVE ESI
eve:
  sso:
    client-id: 5cff565de7eb4060939f4fe4270f064e
    client-secret: eat_0TJ3VbK3DNWqzNEuzfLTtwAHBLdpgFTU_115kaw
    callback-url: http://8.162.26.199:80/eve/callback
    auth-url: https://login.eveonline.com/v2/oauth/authorize
    token-url: https://login.eveonline.com/v2/oauth/token
    user-info-url: https://login.eveonline.com/oauth/verify