server:
  post: 8081

spring:
  application:
    name: eve-system

  # 环境配置
  profiles:
    active: dev
    # active: test
    # active: prod

  # Nacos
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
      config:
        server-addr: nacos:8848
        file-extension: yaml
        import-check:
          enabled: false

# MyBatis-Plus 配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# EVE ESI
eve:
  expire:
    access-token: 1100
    refresh-token: 604800