server:
  port: 8080

spring:
  application:
    name: gatewaySystem

  # 环境配置
  profiles:
    active: dev
    # active: test
    # active: prod

  # Nacos
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848

    # 网关核心配置
    gateway:

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      # 路由规则
      routes:
        # 用户微服务
        - id: user-system
          uri: lb://user-system  # lb = 负载均衡
          predicates:
            - Path=/auth/**

          # eve 微服务
        - id: eve-system
          uri: lb://eve-system
          predicates:
            - Path=/eve/**

      # 跨域配置
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"

# RocketMQ 配置
rocketmq:
  name-server: rocketmq-namesrv:9876

token-bucket:
  enable: true
  rate: 10
  capacity: 20
  expire: 60